//
//  OptionItem.swift
//  CurrencyApp
//
//  Created by Oko-osi Korede on 05/02/2024.
//

import Foundation
protocol OptionItemInterface: GetFlagInterface {
    var optionList: [CurrencyItemInterface] { get }
}

extension OptionItemInterface {
    var optionList: [CurrencyItemInterface] {
        [
            CurrencyItem(value: "AED", icon: getFlag(for: "AED")),
            CurrencyItem(value: "AFN", icon: getFlag(for: "AFN")),
            CurrencyItem(value: "ALL", icon: getFlag(for: "ALL")),
            CurrencyItem(value: "AMD", icon: getFlag(for: "AMD")),
            CurrencyItem(value: "ANG", icon: getFlag(for: "ANG")),
            CurrencyItem(value: "AOA", icon: getFlag(for: "AOA")),
            CurrencyItem(value: "ARS", icon: getFlag(for: "ARS")),
            CurrencyItem(value: "AUD", icon: getFlag(for: "AUD")),
            CurrencyItem(value: "AWG", icon: getFlag(for: "AWG")),
            CurrencyItem(value: "AZN", icon: getFlag(for: "AZN")),
            CurrencyItem(value: "BAM", icon: getFlag(for: "BAM")),
            CurrencyItem(value: "BBD", icon: getFlag(for: "BBD")),
            CurrencyItem(value: "BDT", icon: getFlag(for: "BDT")),
            CurrencyItem(value: "BGN", icon: getFlag(for: "BGN")),
            CurrencyItem(value: "BHD", icon: getFlag(for: "BHD")),
            CurrencyItem(value: "BIF", icon: getFlag(for: "BIF")),
            CurrencyItem(value: "BMD", icon: getFlag(for: "BMD")),
            CurrencyItem(value: "BND", icon: getFlag(for: "BND")),
            CurrencyItem(value: "BOB", icon: getFlag(for: "BOB")),
            CurrencyItem(value: "BRL", icon: getFlag(for: "BRL")),
            CurrencyItem(value: "BSD", icon: getFlag(for: "BSD")),
            CurrencyItem(value: "BTC", icon: getFlag(for: "BTC")),
            CurrencyItem(value: "BTN", icon: getFlag(for: "BTN")),
            CurrencyItem(value: "BWP", icon: getFlag(for: "BWP")),
            CurrencyItem(value: "BYN", icon: getFlag(for: "BYN")),
            CurrencyItem(value: "BYR", icon: getFlag(for: "BYR")),
            CurrencyItem(value: "BZD", icon: getFlag(for: "BZD")),
            CurrencyItem(value: "CAD", icon: getFlag(for: "CAD")),
            CurrencyItem(value: "CDF", icon: getFlag(for: "CDF")),
            CurrencyItem(value: "CHF", icon: getFlag(for: "CHF")),
            CurrencyItem(value: "CLF", icon: getFlag(for: "CLF")),
            CurrencyItem(value: "CLP", icon: getFlag(for: "CLP")),
            CurrencyItem(value: "CNY", icon: getFlag(for: "CNY")),
            CurrencyItem(value: "COP", icon: getFlag(for: "COP")),
            CurrencyItem(value: "CRC", icon: getFlag(for: "CRC")),
            CurrencyItem(value: "CUC", icon: getFlag(for: "CUC")),
            CurrencyItem(value: "CUP", icon: getFlag(for: "CUP")),
            CurrencyItem(value: "CVE", icon: getFlag(for: "CVE")),
            CurrencyItem(value: "CZK", icon: getFlag(for: "CZK")),
            CurrencyItem(value: "DJF", icon: getFlag(for: "DJF")),
            CurrencyItem(value: "DKK", icon: getFlag(for: "DKK")),
            CurrencyItem(value: "DOP", icon: getFlag(for: "DOP")),
            CurrencyItem(value: "DZD", icon: getFlag(for: "DZD")),
            CurrencyItem(value: "EGP", icon: getFlag(for: "EGP")),
            CurrencyItem(value: "ERN", icon: getFlag(for: "ERN")),
            CurrencyItem(value: "ETB", icon: getFlag(for: "ETB")),
            CurrencyItem(value: "EUR", icon: getFlag(for: "EUR")),
            CurrencyItem(value: "FJD", icon: getFlag(for: "FJD")),
            CurrencyItem(value: "FKP", icon: getFlag(for: "FKP")),
            CurrencyItem(value: "GBP", icon: getFlag(for: "GBP")),
            CurrencyItem(value: "GEL", icon: getFlag(for: "GEL")),
            CurrencyItem(value: "GGP", icon: getFlag(for: "GGP")),
            CurrencyItem(value: "GHS", icon: getFlag(for: "GHS")),
            CurrencyItem(value: "GIP", icon: getFlag(for: "GIP")),
            CurrencyItem(value: "GMD", icon: getFlag(for: "GMD")),
            CurrencyItem(value: "GNF", icon: getFlag(for: "GNF")),
            CurrencyItem(value: "GTQ", icon: getFlag(for: "GTQ")),
            CurrencyItem(value: "GYD", icon: getFlag(for: "GYD")),
            CurrencyItem(value: "HKD", icon: getFlag(for: "HKD")),
            CurrencyItem(value: "HNL", icon: getFlag(for: "HNL")),
            CurrencyItem(value: "HRK", icon: getFlag(for: "HRK")),
            CurrencyItem(value: "HTG", icon: getFlag(for: "HTG")),
            CurrencyItem(value: "HUF", icon: getFlag(for: "HUF")),
            CurrencyItem(value: "IDR", icon: getFlag(for: "IDR")),
            CurrencyItem(value: "ILS", icon: getFlag(for: "ILS")),
            CurrencyItem(value: "IMP", icon: getFlag(for: "IMP")),
            CurrencyItem(value: "INR", icon: getFlag(for: "INR")),
            CurrencyItem(value: "IQD", icon: getFlag(for: "IQD")),
            CurrencyItem(value: "IRR", icon: getFlag(for: "IRR")),
            CurrencyItem(value: "ISK", icon: getFlag(for: "ISK")),
            CurrencyItem(value: "JEP", icon: getFlag(for: "JEP")),
            CurrencyItem(value: "JMD", icon: getFlag(for: "JMD")),
            CurrencyItem(value: "JOD", icon: getFlag(for: "JOD")),
            CurrencyItem(value: "JPY", icon: getFlag(for: "JPY")),
            CurrencyItem(value: "KES", icon: getFlag(for: "KES")),
            CurrencyItem(value: "KGS", icon: getFlag(for: "KGS")),
            CurrencyItem(value: "KHR", icon: getFlag(for: "KHR")),
            CurrencyItem(value: "KMF", icon: getFlag(for: "KMF")),
            CurrencyItem(value: "KPW", icon: getFlag(for: "KPW")),
            CurrencyItem(value: "KRW", icon: getFlag(for: "KRW")),
            CurrencyItem(value: "KWD", icon: getFlag(for: "KWD")),
            CurrencyItem(value: "KYD", icon: getFlag(for: "KYD")),
            CurrencyItem(value: "KZT", icon: getFlag(for: "KZT")),
            CurrencyItem(value: "LAK", icon: getFlag(for: "LAK")),
            CurrencyItem(value: "LBP", icon: getFlag(for: "LBP")),
            CurrencyItem(value: "LKR", icon: getFlag(for: "LKR")),
            CurrencyItem(value: "LRD", icon: getFlag(for: "LRD")),
            CurrencyItem(value: "LSL", icon: getFlag(for: "LSL")),
            CurrencyItem(value: "LTL", icon: getFlag(for: "LTL")),
            CurrencyItem(value: "LVL", icon: getFlag(for: "LVL")),
            CurrencyItem(value: "LYD", icon: getFlag(for: "LYD")),
            CurrencyItem(value: "MAD", icon: getFlag(for: "MAD")),
            CurrencyItem(value: "MDL", icon: getFlag(for: "MDL")),
            CurrencyItem(value: "MGA", icon: getFlag(for: "MGA")),
            CurrencyItem(value: "MKD", icon: getFlag(for: "MKD")),
            CurrencyItem(value: "MMK", icon: getFlag(for: "MMK")),
            CurrencyItem(value: "MNT", icon: getFlag(for: "MNT")),
            CurrencyItem(value: "MOP", icon: getFlag(for: "MOP")),
            CurrencyItem(value: "MRU", icon: getFlag(for: "MRU")),
            CurrencyItem(value: "MUR", icon: getFlag(for: "MUR")),
            CurrencyItem(value: "MVR", icon: getFlag(for: "MVR")),
            CurrencyItem(value: "MWK", icon: getFlag(for: "MWK")),
            CurrencyItem(value: "MXN", icon: getFlag(for: "MXN")),
            CurrencyItem(value: "MYR", icon: getFlag(for: "MYR")),
            CurrencyItem(value: "MZN", icon: getFlag(for: "MZN")),
            CurrencyItem(value: "NAD", icon: getFlag(for: "NAD")),
            CurrencyItem(value: "NGN", icon: getFlag(for: "NGN")),
            CurrencyItem(value: "NIO", icon: getFlag(for: "NIO")),
            CurrencyItem(value: "NOK", icon: getFlag(for: "NOK")),
            CurrencyItem(value: "NPR", icon: getFlag(for: "NPR")),
            CurrencyItem(value: "NZD", icon: getFlag(for: "NZD")),
            CurrencyItem(value: "OMR", icon: getFlag(for: "OMR")),
            CurrencyItem(value: "PAB", icon: getFlag(for: "PAB")),
            CurrencyItem(value: "PEN", icon: getFlag(for: "PEN")),
            CurrencyItem(value: "PGK", icon: getFlag(for: "PGK")),
            CurrencyItem(value: "PHP", icon: getFlag(for: "PHP")),
            CurrencyItem(value: "PKR", icon: getFlag(for: "PKR")),
            CurrencyItem(value: "PLN", icon: getFlag(for: "PLN")),
            CurrencyItem(value: "PYG", icon: getFlag(for: "PYG")),
            CurrencyItem(value: "QAR", icon: getFlag(for: "QAR")),
            CurrencyItem(value: "RON", icon: getFlag(for: "RON")),
            CurrencyItem(value: "RSD", icon: getFlag(for: "RSD")),
            CurrencyItem(value: "RUB", icon: getFlag(for: "RUB")),
            CurrencyItem(value: "RWF", icon: getFlag(for: "RWF")),
            CurrencyItem(value: "SAR", icon: getFlag(for: "SAR")),
            CurrencyItem(value: "SBD", icon: getFlag(for: "SBD")),
            CurrencyItem(value: "SCR", icon: getFlag(for: "SCR")),
            CurrencyItem(value: "SDG", icon: getFlag(for: "SDG")),
            CurrencyItem(value: "SEK", icon: getFlag(for: "SEK")),
            CurrencyItem(value: "SGD", icon: getFlag(for: "SGD")),
            CurrencyItem(value: "SHP", icon: getFlag(for: "SHP")),
            CurrencyItem(value: "SLE", icon: getFlag(for: "SLE")),
            CurrencyItem(value: "SLL", icon: getFlag(for: "SLL")),
            CurrencyItem(value: "SOS", icon: getFlag(for: "SOS")),
            CurrencyItem(value: "SRD", icon: getFlag(for: "SRD")),
            CurrencyItem(value: "STD", icon: getFlag(for: "STD")),
            CurrencyItem(value: "SYP", icon: getFlag(for: "SYP")),
            CurrencyItem(value: "SZL", icon: getFlag(for: "SZL")),
            CurrencyItem(value: "THB", icon: getFlag(for: "THB")),
            CurrencyItem(value: "TJS", icon: getFlag(for: "TJS")),
            CurrencyItem(value: "TMT", icon: getFlag(for: "TMT")),
            CurrencyItem(value: "TND", icon: getFlag(for: "TND")),
            CurrencyItem(value: "TOP", icon: getFlag(for: "TOP")),
            CurrencyItem(value: "TRY", icon: getFlag(for: "TRY")),
            CurrencyItem(value: "TTD", icon: getFlag(for: "TTD")),
            CurrencyItem(value: "TWD", icon: getFlag(for: "TWD")),
            CurrencyItem(value: "TZS", icon: getFlag(for: "TZS")),
            CurrencyItem(value: "UAH", icon: getFlag(for: "UAH")),
            CurrencyItem(value: "UGX", icon: getFlag(for: "UGX")),
            CurrencyItem(value: "USD", icon: getFlag(for: "USD")),
            CurrencyItem(value: "UYU", icon: getFlag(for: "UYU")),
            CurrencyItem(value: "UZS", icon: getFlag(for: "UZS")),
            CurrencyItem(value: "VEF", icon: getFlag(for: "VEF")),
            CurrencyItem(value: "VES", icon: getFlag(for: "VES")),
            CurrencyItem(value: "VND", icon: getFlag(for: "VND")),
            CurrencyItem(value: "VUV", icon: getFlag(for: "VUV")),
            CurrencyItem(value: "WST", icon: getFlag(for: "WST")),
            CurrencyItem(value: "XAF", icon: getFlag(for: "XAF")),
            CurrencyItem(value: "XAG", icon: getFlag(for: "XAG")),
            CurrencyItem(value: "XAU", icon: getFlag(for: "XAU")),
            CurrencyItem(value: "XCD", icon: getFlag(for: "XCD")),
            CurrencyItem(value: "XDR", icon: getFlag(for: "XDR")),
            CurrencyItem(value: "XOF", icon: getFlag(for: "XOF")),
            CurrencyItem(value: "XPF", icon: getFlag(for: "XPF")),
            CurrencyItem(value: "YER", icon: getFlag(for: "YER")),
            CurrencyItem(value: "ZAR", icon: getFlag(for: "ZAR")),
            CurrencyItem(value: "ZMK", icon: getFlag(for: "ZMK")),
            CurrencyItem(value: "ZMW", icon: getFlag(for: "ZMW")),
            CurrencyItem(value: "ZWL", icon: getFlag(for: "ZWL"))
        ]
    }
}
